### ISSUE TITLE
Option to change color to black for text and icons

### ISSUE THREAD

**Issue by ps13g** [JulienMaille/dribbblish-dynamic-theme#106]
Hey guys, I feel that we need an option in the settings to change the friends activity text to black and the icons also to black because sometimes the white does not follow well with certain colors and it can be frustrating at times.

FYI: This used to exist before 3.1.0 as a small workaround by doing spicetify config color_scheme but it was recently removed from the updates.

**Comment by JulienMaille** [comment]
Please share an exemple showing the problematic font color.

**Comment by ps13g** [comment]
![image](https://user-images.githubusercontent.com/84423124/141319719-3fcfc97e-3dad-403f-8a1a-1f9c236f6423.png)
![image](https://user-images.githubusercontent.com/84423124/141319818-14908331-df52-4e70-8f71-92b34c8d9674.png)
 
Before 3.1.0 there was a way in changing this to black unofficially but since 3.1.0 there is no way to change the color to black so what I suggest is that we need setting that can let the user change it to black

**Comment by JulienMaille** [comment]
A black font in your screenshot would result in unreadable text.

**Comment by Davoleo** [comment]
About this, more than a configuration option it would be cool if the forecolor adapted depending on the color of the background, because there are some cases where text becomes unreadable there
Examples:
Song: https://open.spotify.com/track/2sf18cEv463VgqmdjDsFpw?si=0199dfec431846f5
![image](https://user-images.githubusercontent.com/24458276/141492016-9935d3d8-0646-4881-be2a-204b8055c27c.png)

Song: https://open.spotify.com/track/0Wjl0wDy3oSn3c4RxF0HpZ?si=110c959358f04b07
![image](https://user-images.githubusercontent.com/24458276/141492114-92d70d54-8a2a-43d4-91f4-ce8232893d65.png)

Most of the time white font color is ok (the issues arise with colors similar to yellow)
but if performance allows it I think having it dyanmic could also increase the range of types of colors you can use from covers.

**Comment by SendNukez** [comment]
Yeah I want to change the way colors are grabbed / used completely. But right now that's not my main focus since that would require a lot of work, and I'm not even completely sure how to go about doing this.

**Comment by JulienMaille** [comment]
Should work out of the box in 4.0.0
