### ISSUE TITLE
Dynamic Colours do not match the album covers at all

### ISSUE THREAD

**Issue by Fuzqi** [JulienMaille/dribbblish-dynamic-theme#110]
**Describe the bug**
The dynamic colours that change with the song cover do not match the song cover at all. For example, Whole Lotta Red by Playboi Carti has a red theme to it however my spotify changes to blue whenever it plays that album and there is so aspect of blue in the cover,

**To Reproduce**
Not really sure, just loaded up spotify and it was bugged,

**Screenshots**
One) https://i.imgur.com/62fRyPp.png
One) Clearly no red in the cover yet it's red?
Two) https://i.imgur.com/4W5ME72.png
Two) There is some orange but it's mainly blue.

**Desktop Setup**
OS: Windows v10.0.22000
Spotify: v1.1.71.560
Spicetify: v2.8.1
Dribbblish: v3.1.1-6f7096b

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtool` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
https://i.imgur.com/i9glcRq.png
```

**Comment by Davoleo** [comment]
I think the colors are there, just in a really small region of the cover, I have noticed this behaviour on low saturated album covers as well

**Comment by SendNukez** [comment]
This is because we're using [node-vibrant](https://github.com/Vibrant-Colors/node-vibrant) (basically just an improved version of [vibrant.js](http://jariz.github.io/vibrant.js/)) which, as the name implies, extracts the vibrant colors from an image. Hence the bright colors. We might switch over to [colorthief](https://lokeshdhakar.com/projects/color-thief/) to get dominant colors, but if we're to use that it would have to be in combination with overhauling the whole color-picking system (#53).
