### ISSUE TITLE
Pick static colour of theme - Instead of just Light/Dark

### ISSUE THREAD

**Issue by crawmptastic** [JulienMaille/dribbblish-dynamic-theme#124]
As title says. I'm sure this can easily be done by changing something in the config file, I just don't know how ✌️ 
Basically just instead of a dark grey/white as the bg colour of the client, I'd like to set it to a specific colour hexcode.

Lmk if/how this can be done, thanks!

**Comment by alixti** [comment]
Go to Dribbblish Settings, then find in theme section "Color Sections Algorithm" and then select "Static" and finally choose your favorite color.

**Comment by crawmptastic** [comment]
Hi, I mean for the background theme (which only has dark/light options) [https://imgur.com/a/l4SHQRf](url)

**Comment by SendNukez** [comment]
This is not really that easy since we expect the colors to be either dark or white for some aspects of the Theme. Implementing this would mean changing / complicating a lot of stuff. The newest (not released yet) build of the theme has a `Custom CSS` option which you could use to change the background color to your liking. You'll have to have some knowledge of CSS though. If you'd like to give it a try you can download [this](https://github.com/JulienMaille/dribbblish-dynamic-theme/suites/4489328469/artifacts/119624059) and follow the [Manual Install](https://github.com/JulienMaille/dribbblish-dynamic-theme#manual-install) steps using this build.

**Comment by JulienMaille** [comment]
@SendNukez we could have 2 or three preset like white/black, nord-light/nord-dark, light grey/dark grey
 What do you think?

**Comment by crawmptastic** [comment]
Ily :)
