### ISSUE TITLE
Colors are difficult to distinct for several album covers

### ISSUE THREAD

**Issue by tetralovania** [JulienMaille/dribbblish-dynamic-theme#169]
**Is your feature request related to a problem? Please describe.**
With some album covers. the colors are really difficult to tell apart (see screenshot for reference, the play button is difficult to make out) 
![image](https://user-images.githubusercontent.com/86831655/153600511-d06ddeab-11e0-463e-8372-58b8832df128.png)

**Describe the solution you'd like**
Not exactly sure how the color picker algorithm works, but you could either just force it to have a certain contrast (like the contrast checker by adobe: https://color.adobe.com/de/create/color-contrast-analyzer) or if "forcing" it doesn't work with the current algorithm, you could either darken the darker color or lighten the lighter color to increase the readability.

**Describe alternatives you've considered**
You could obviously also use the user-picked color for the theme, but this isn't guaranteed to be contrast-rich either afaik.

**Additional context**
a few more examples:
![image](https://user-images.githubusercontent.com/86831655/153601175-bf8691e8-54e4-4006-971c-e5cc35e3a1c6.png)
![image](https://user-images.githubusercontent.com/86831655/153601240-e0450d2b-1206-498b-bf43-d787e8910921.png)
![image](https://user-images.githubusercontent.com/86831655/153601316-d6ff2301-9e8a-41f9-a675-a613b81d20ab.png)
![image](https://user-images.githubusercontent.com/86831655/153601375-3d010be0-40c6-4862-ad4a-0f724f288edb.png)
(this also effects other buttons like the little heart in the liked songs by this artis icon and several plugin windows that use the colors.)

**Comment by Davoleo** [comment]
I think that issue here is more like some style that is not being applied correctly on those FAB round buttons throughout the application more than color picking being wrong; in the rest of the app color contrast is totally fine for me

This is also backed by an issue I've noticed while hovering on those kind of buttons: the default spotify green shows up, even when another color is currently selected.

#### Examples
Not Hovering:
![image](https://user-images.githubusercontent.com/24458276/153606725-2a645e71-9544-4e5f-822a-bba4f1f191e3.png)
Hovering:
![image](https://user-images.githubusercontent.com/24458276/153606744-8cd76ae7-5a22-411a-aaff-7cf23bafcf6f.png)

The selected color from the cover looks like: `BF080F`

**Comment by tetralovania** [comment]
Sorry if that's a stupid question, but do you mean some style that is not being applied by the theme dev or did I miss something?

**Comment by JulienMaille** [comment]
I believe latest Spotify updates partially broke theming: https://github.com/khanhas/spicetify-cli/issues/1468
