### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by SendNukez** [JulienMaille/dribbblish-dynamic-theme#98]
There is a method `Spicetify.Locale.getLocale()` which returns the language Spotify is set to, e.g. `en`. We could use this and create a folder inside src where locales are stored as `en.json`, `[...]`  and would be bundled inside the `dist/dribbblish-dynamic.js`. We then have a class to parse / get these locales and if something isn't available in the current locale we just fall back to English for that string. I could add the German locale.

What do you think @JulienMaille?

**Comment by JulienMaille** [comment]
I suppose you want to translate the settings?

**Comment by SendNukez** [comment]
Yes, that's the only part of this theme that displays its own text.

**Comment by SendNukez** [comment]
I just thought it would be kind of weird if you had Spotify set to say Spanish and the settings were still in English. When first implementing this we won't have every language, but I'm guessing people who have set Spotify to different languages would likely help us translate.

**Comment by JulienMaille** [comment]
Sounds a bit overkill to me tbh

**Comment by SendNukez** [comment]
Yeah I guess so, but I still think this would be a nice addition. Maybe we can add it in the future.

**Comment by alixti** [comment]
It sounds like a nice enhancement and it would be nice to see it working on the theme. I have a few ideas I'd like to share with you: Instead of using a JSON file you could directly use a script containing the whole array of strings and you could avoid the "parsing" step. Also, instead of bundling the localization file with everything else I think it would be better to let the user download it individually. I don't know, that way wouldn't make the file bigger and let unnecessary stuff like other languages that the user won't even use.

**Comment by JulienMaille** [comment]
I think nobody has time for this unfortunately
